// PCodeOpcode.cpp - P-Code opcode lookup tables and metadata
// Part of VBDecompiler - Visual Basic 5/6 Decompiler
//
// Implements P-Code opcode definitions, format strings, and lookup functions
// for the stack-based VB bytecode instruction set.

#include "PCodeOpcode.h"
#include <array>

namespace VBDecompiler {

// ============================================================================
// Opcode Lookup Tables
// ============================================================================

// Standard opcodes (0x00-0xFF)
// Format: opcode, extOpcode, mnemonic, format, category, stackDelta,
//         isExtended, isBranch, isConditionalBranch, isCall, isReturn
static constexpr std::array<PCodeOpcodeInfo, 256> standardOpcodes = {{
    {0x00, 0x00, "Unknown00", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x01, 0x00, "Unknown01", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x02, 0x00, "Unknown02", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x03, 0x00, "Unknown03", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x04, 0x00, "FLdRfVar", "a", PCodeOpcodeCategory::VARIABLE, 1, false, false, false, false, false},
    {0x05, 0x00, "ImpAdLdRf", "c", PCodeOpcodeCategory::CALL, 1, false, false, false, false, false},
    {0x06, 0x00, "Unknown06", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x07, 0x00, "Unknown07", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x08, 0x00, "Unknown08", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x09, 0x00, "ImpAdCallHresult", "", PCodeOpcodeCategory::CALL, 0, false, false, false, true, false},
    {0x0A, 0x00, "ImpAdCallFPR4", "x", PCodeOpcodeCategory::CALL, 0, false, false, false, true, false},
    {0x0B, 0x00, "Unknown0B", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x0C, 0x00, "Unknown0C", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x0D, 0x00, "VCallHresult", "v", PCodeOpcodeCategory::CALL, 0, false, false, false, true, false},
    {0x0E, 0x00, "Unknown0E", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x0F, 0x00, "Unknown0F", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x10, 0x00, "Unknown10", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x11, 0x00, "Unknown11", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x12, 0x00, "Unknown12", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x13, 0x00, "ExitProcHresult", "", PCodeOpcodeCategory::CONTROL_FLOW, 0, false, false, false, false, true},
    {0x14, 0x00, "ExitProc", "", PCodeOpcodeCategory::CONTROL_FLOW, 0, false, false, false, false, true},
    {0x15, 0x00, "Unknown15", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x16, 0x00, "Unknown16", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x17, 0x00, "Unknown17", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x18, 0x00, "Unknown18", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x19, 0x00, "Unknown19", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x1A, 0x00, "FFree1Ad", "", PCodeOpcodeCategory::MEMORY, 0, false, false, false, false, false},
    {0x1B, 0x00, "LitStr", "z", PCodeOpcodeCategory::STACK, 1, false, false, false, false, false},
    {0x1C, 0x00, "BranchF", "l", PCodeOpcodeCategory::CONTROL_FLOW, -1, false, true, true, false, false},
    {0x1D, 0x00, "BranchT", "l", PCodeOpcodeCategory::CONTROL_FLOW, -1, false, true, true, false, false},
    {0x1E, 0x00, "Branch", "l", PCodeOpcodeCategory::CONTROL_FLOW, 0, false, true, false, false, false},
    {0x1F, 0x00, "Unknown1F", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x20, 0x00, "Unknown20", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x21, 0x00, "Unknown21", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x22, 0x00, "Unknown22", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x23, 0x00, "Unknown23", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x24, 0x00, "Unknown24", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x25, 0x00, "Unknown25", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x26, 0x00, "Unknown26", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x27, 0x00, "LitVar_Missing", "", PCodeOpcodeCategory::STACK, 1, false, false, false, false, false},
    {0x28, 0x00, "LitVarI2", "a%", PCodeOpcodeCategory::STACK, 1, false, false, false, false, false},
    {0x29, 0x00, "FFreeAd", "", PCodeOpcodeCategory::MEMORY, 0, false, false, false, false, false},
    {0x2A, 0x00, "ConcatStr", "", PCodeOpcodeCategory::STRING, -1, false, false, false, false, false},
    {0x2B, 0x00, "Unknown2B", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x2C, 0x00, "Unknown2C", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x2D, 0x00, "Unknown2D", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x2E, 0x00, "Unknown2E", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x2F, 0x00, "FFree1Str", "", PCodeOpcodeCategory::STRING, 0, false, false, false, false, false},
    {0x30, 0x00, "Unknown30", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x31, 0x00, "Unknown31", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x32, 0x00, "FFreeStr", "", PCodeOpcodeCategory::STRING, 0, false, false, false, false, false},
    {0x33, 0x00, "LdFixedStr", "z", PCodeOpcodeCategory::STRING, 1, false, false, false, false, false},
    {0x34, 0x00, "CStr2Ansi", "", PCodeOpcodeCategory::STRING, 0, false, false, false, false, false},
    {0x35, 0x00, "FFree1Var", "", PCodeOpcodeCategory::MEMORY, 0, false, false, false, false, false},
    {0x36, 0x00, "FFreeVar", "", PCodeOpcodeCategory::MEMORY, 0, false, false, false, false, false},
    {0x37, 0x00, "Unknown37", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x38, 0x00, "Unknown38", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x39, 0x00, "Unknown39", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x3A, 0x00, "LitVarStr", "az", PCodeOpcodeCategory::STACK, 1, false, false, false, false, false},
    {0x3B, 0x00, "Ary1StStrCopy", "", PCodeOpcodeCategory::ARRAY, -2, false, false, false, false, false},
    {0x3C, 0x00, "Unknown3C", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x3D, 0x00, "Unknown3D", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x3E, 0x00, "Unknown3E", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x3F, 0x00, "Unknown3F", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x40, 0x00, "Ary1LdRf", "", PCodeOpcodeCategory::ARRAY, 0, false, false, false, false, false},
    {0x41, 0x00, "Ary1LdPr", "", PCodeOpcodeCategory::ARRAY, 0, false, false, false, false, false},
    {0x42, 0x00, "Unknown42", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x43, 0x00, "FStStrCopy", "a", PCodeOpcodeCategory::STRING, -1, false, false, false, false, false},
    {0x44, 0x00, "Unknown44", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x45, 0x00, "Unknown45", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x46, 0x00, "Unknown46", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x47, 0x00, "Unknown47", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x48, 0x00, "Unknown48", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x49, 0x00, "Unknown49", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x4A, 0x00, "FnLenStr", "", PCodeOpcodeCategory::STRING, 0, false, false, false, false, false},
    {0x4B, 0x00, "OnErrorGoto", "l", PCodeOpcodeCategory::CONTROL_FLOW, 0, false, false, false, false, false},
    {0x4C, 0x00, "Unknown4C", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x4D, 0x00, "Unknown4D", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x4E, 0x00, "Unknown4E", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x4F, 0x00, "Unknown4F", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x50, 0x00, "Unknown50", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x51, 0x00, "Unknown51", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x52, 0x00, "Ary1StVar", "", PCodeOpcodeCategory::ARRAY, -2, false, false, false, false, false},
    {0x53, 0x00, "Unknown53", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x54, 0x00, "Unknown54", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x55, 0x00, "Unknown55", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x56, 0x00, "Unknown56", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x57, 0x00, "Unknown57", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x58, 0x00, "Unknown58", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x59, 0x00, "Unknown59", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x5A, 0x00, "Erase", "", PCodeOpcodeCategory::ARRAY, 0, false, false, false, false, false},
    {0x5B, 0x00, "Unknown5B", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x5C, 0x00, "Unknown5C", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x5D, 0x00, "Unknown5D", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x5E, 0x00, "ImpAdCallI4", "x", PCodeOpcodeCategory::CALL, 0, false, false, false, true, false},
    {0x5F, 0x00, "Unknown5F", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x60, 0x00, "Unknown60", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x61, 0x00, "Unknown61", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x62, 0x00, "Unknown62", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x63, 0x00, "LitVar_TRUE", "", PCodeOpcodeCategory::STACK, 1, false, false, false, false, false},
    {0x64, 0x00, "NextI2", "", PCodeOpcodeCategory::LOOP, 0, false, true, false, false, false},
    {0x65, 0x00, "NextStepI2", "", PCodeOpcodeCategory::LOOP, 0, false, true, false, false, false},
    {0x66, 0x00, "NextI4", "", PCodeOpcodeCategory::LOOP, 0, false, true, false, false, false},
    {0x67, 0x00, "NextStepI4", "", PCodeOpcodeCategory::LOOP, 0, false, true, false, false, false},
    {0x68, 0x00, "NextStepR4", "", PCodeOpcodeCategory::LOOP, 0, false, true, false, false, false},
    {0x69, 0x00, "NextStepR8", "", PCodeOpcodeCategory::LOOP, 0, false, true, false, false, false},
    {0x6A, 0x00, "Unknown6A", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x6B, 0x00, "FLdI2", "a", PCodeOpcodeCategory::VARIABLE, 1, false, false, false, false, false},
    {0x6C, 0x00, "Unknown6C", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x6D, 0x00, "Unknown6D", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x6E, 0x00, "Unknown6E", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x6F, 0x00, "Unknown6F", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x70, 0x00, "FStI2", "a", PCodeOpcodeCategory::VARIABLE, -1, false, false, false, false, false},
    {0x71, 0x00, "Unknown71", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x72, 0x00, "Unknown72", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x73, 0x00, "Unknown73", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x74, 0x00, "Unknown74", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x75, 0x00, "Unknown75", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x76, 0x00, "Unknown76", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x77, 0x00, "Unknown77", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x78, 0x00, "Unknown78", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x79, 0x00, "Unknown79", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x7A, 0x00, "Unknown7A", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x7B, 0x00, "Unknown7B", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x7C, 0x00, "Unknown7C", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x7D, 0x00, "Unknown7D", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x7E, 0x00, "Unknown7E", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x7F, 0x00, "ILdI2", "a", PCodeOpcodeCategory::VARIABLE, 1, false, false, false, false, false},
    {0x80, 0x00, "ILdI4", "a", PCodeOpcodeCategory::VARIABLE, 1, false, false, false, false, false},
    {0x81, 0x00, "Unknown81", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x82, 0x00, "Unknown82", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x83, 0x00, "Unknown83", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x84, 0x00, "IStI2", "c", PCodeOpcodeCategory::VARIABLE, -1, false, false, false, false, false},
    {0x85, 0x00, "Unknown85", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x86, 0x00, "Unknown86", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x87, 0x00, "Unknown87", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x88, 0x00, "Unknown88", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x89, 0x00, "Unknown89", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x8A, 0x00, "Unknown8A", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x8B, 0x00, "Unknown8B", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x8C, 0x00, "Unknown8C", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x8D, 0x00, "Unknown8D", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x8E, 0x00, "Unknown8E", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x8F, 0x00, "Unknown8F", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x90, 0x00, "Unknown90", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x91, 0x00, "Unknown91", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x92, 0x00, "Unknown92", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x93, 0x00, "Unknown93", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x94, 0x00, "Unknown94", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x95, 0x00, "Unknown95", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x96, 0x00, "Unknown96", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x97, 0x00, "Unknown97", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x98, 0x00, "Unknown98", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x99, 0x00, "Unknown99", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x9A, 0x00, "Unknown9A", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x9B, 0x00, "Unknown9B", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x9C, 0x00, "Unknown9C", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x9D, 0x00, "Unknown9D", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x9E, 0x00, "Unknown9E", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0x9F, 0x00, "Unknown9F", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xA0, 0x00, "UnknownA0", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xA1, 0x00, "UnknownA1", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xA2, 0x00, "UnknownA2", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xA3, 0x00, "UnknownA3", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xA4, 0x00, "UnknownA4", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xA5, 0x00, "UnknownA5", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xA6, 0x00, "UnknownA6", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xA7, 0x00, "UnknownA7", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xA8, 0x00, "UnknownA8", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xA9, 0x00, "UnknownA9", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xAA, 0x00, "UnknownAA", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xAB, 0x00, "UnknownAB", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xAC, 0x00, "UnknownAC", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xAD, 0x00, "UnknownAD", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xAE, 0x00, "UnknownAE", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xAF, 0x00, "UnknownAF", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xB0, 0x00, "UnknownB0", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xB1, 0x00, "UnknownB1", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xB2, 0x00, "UnknownB2", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xB3, 0x00, "UnknownB3", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xB4, 0x00, "UnknownB4", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xB5, 0x00, "UnknownB5", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xB6, 0x00, "UnknownB6", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xB7, 0x00, "UnknownB7", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xB8, 0x00, "UnknownB8", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xB9, 0x00, "UnknownB9", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xBA, 0x00, "UnknownBA", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xBB, 0x00, "UnknownBB", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xBC, 0x00, "UnknownBC", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xBD, 0x00, "UnknownBD", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xBE, 0x00, "UnknownBE", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xBF, 0x00, "UnknownBF", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xC0, 0x00, "UnknownC0", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xC1, 0x00, "UnknownC1", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xC2, 0x00, "UnknownC2", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xC3, 0x00, "UnknownC3", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xC4, 0x00, "UnknownC4", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xC5, 0x00, "UnknownC5", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xC6, 0x00, "UnknownC6", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xC7, 0x00, "UnknownC7", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xC8, 0x00, "UnknownC8", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xC9, 0x00, "UnknownC9", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xCA, 0x00, "UnknownCA", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xCB, 0x00, "UnknownCB", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xCC, 0x00, "UnknownCC", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xCD, 0x00, "UnknownCD", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xCE, 0x00, "UnknownCE", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xCF, 0x00, "UnknownCF", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xD0, 0x00, "UnknownD0", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xD1, 0x00, "UnknownD1", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xD2, 0x00, "UnknownD2", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xD3, 0x00, "UnknownD3", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xD4, 0x00, "UnknownD4", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xD5, 0x00, "UnknownD5", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xD6, 0x00, "UnknownD6", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xD7, 0x00, "UnknownD7", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xD8, 0x00, "UnknownD8", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xD9, 0x00, "UnknownD9", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xDA, 0x00, "UnknownDA", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xDB, 0x00, "UnknownDB", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xDC, 0x00, "UnknownDC", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xDD, 0x00, "UnknownDD", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xDE, 0x00, "UnknownDE", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xDF, 0x00, "UnknownDF", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xE0, 0x00, "UnknownE0", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xE1, 0x00, "UnknownE1", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xE2, 0x00, "UnknownE2", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xE3, 0x00, "UnknownE3", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xE4, 0x00, "UnknownE4", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xE5, 0x00, "UnknownE5", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xE6, 0x00, "UnknownE6", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xE7, 0x00, "UnknownE7", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xE8, 0x00, "UnknownE8", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xE9, 0x00, "UnknownE9", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xEA, 0x00, "UnknownEA", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xEB, 0x00, "UnknownEB", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xEC, 0x00, "UnknownEC", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xED, 0x00, "UnknownED", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xEE, 0x00, "UnknownEE", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xEF, 0x00, "UnknownEF", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xF0, 0x00, "UnknownF0", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xF1, 0x00, "UnknownF1", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xF2, 0x00, "UnknownF2", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xF3, 0x00, "UnknownF3", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xF4, 0x00, "UnknownF4", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xF5, 0x00, "UnknownF5", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xF6, 0x00, "UnknownF6", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xF7, 0x00, "UnknownF7", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xF8, 0x00, "UnknownF8", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xF9, 0x00, "UnknownF9", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xFA, 0x00, "UnknownFA", "", PCodeOpcodeCategory::UNKNOWN, 0, false, false, false, false, false},
    {0xFB, 0x00, "ExtendedFB", "", PCodeOpcodeCategory::UNKNOWN, 0, true, false, false, false, false},
    {0xFC, 0x00, "ExtendedFC", "", PCodeOpcodeCategory::UNKNOWN, 0, true, false, false, false, false},
    {0xFD, 0x00, "ExtendedFD", "", PCodeOpcodeCategory::UNKNOWN, 0, true, false, false, false, false},
    {0xFE, 0x00, "ExtendedFE", "", PCodeOpcodeCategory::UNKNOWN, 0, true, false, false, false, false},
    {0xFF, 0x00, "ExtendedFF", "", PCodeOpcodeCategory::UNKNOWN, 0, true, false, false, false, false},
}};

// ============================================================================
// Public API Functions
// ============================================================================

const PCodeOpcodeInfo* getOpcodeInfo(uint8_t opcode) {
    return &standardOpcodes[opcode];
}

const PCodeOpcodeInfo* getExtendedOpcodeInfo(uint8_t prefix, uint8_t opcode) {
    // Extended opcodes are not fully documented yet
    // Return nullptr for now - will be implemented as we discover them
    (void)prefix;
    (void)opcode;
    return nullptr;
}

std::string_view getCategoryName(PCodeOpcodeCategory category) {
    switch (category) {
        case PCodeOpcodeCategory::CONTROL_FLOW: return "Control Flow";
        case PCodeOpcodeCategory::STACK: return "Stack";
        case PCodeOpcodeCategory::VARIABLE: return "Variable";
        case PCodeOpcodeCategory::CALL: return "Call";
        case PCodeOpcodeCategory::STRING: return "String";
        case PCodeOpcodeCategory::ARRAY: return "Array";
        case PCodeOpcodeCategory::LOOP: return "Loop";
        case PCodeOpcodeCategory::MEMORY: return "Memory";
        case PCodeOpcodeCategory::ARITHMETIC: return "Arithmetic";
        case PCodeOpcodeCategory::LOGICAL: return "Logical";
        case PCodeOpcodeCategory::COMPARISON: return "Comparison";
        case PCodeOpcodeCategory::CONVERSION: return "Conversion";
        case PCodeOpcodeCategory::UNKNOWN: return "Unknown";
        default: return "Invalid";
    }
}

} // namespace VBDecompiler
